---
services:
  app:
    image: hunzo/flask-session-redis
    ports: [80:5000]
    environment: [REDIS_SERVER=redis]
    networks: [net]
  redis:
    image: redis
    ports: [6379:6379]
    networks: [net]
networks:
  net:
