---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp:
  labels:
    app: app
  name: app
  namespace: flask-session
spec:
  ports:
    - name: 8081-5000
      port: 8081
      protocol: TCP
      targetPort: 5000
  selector:
    app: app
  type: LoadBalancer
status:
  loadBalancer: {}
